sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: u3msXM5bnoAwwyyB9CWA38oN+Cn6RYJZjXPbFLaAGgoAx6EPHr6ufP+AUg+cOTJ7IdJxT10Mdpd3bU0SCNLvTZCTn/8QtrauTTgyCQ8SvYvYnlui6tnJfdfAS4i3KLeZz1WXKrmbg5kYogt5s2tiQH0FG0tMmchPyUykzsoXIKa6Exd2PTqfYJO7x2x2AEq+tqPl/YZ/pG6OyPrAIh7HY7A+y1hxt9ElHPjOhMaC/BaP7giuH0x+KEClZTbgckezNhSeFU1Y+xrFmv482DUjZGyx0nv/e1k34IOnBso9ODJ66eNP5orUWqd2dTX1X73gzx5qXFQi82Sb36959klfC8o94qB7yz4NecUu6OTpr3kv/lHLXrsT06FgU/e8q7tOZYpYLDapF1w0h4g/HHV5VLxGM9FMZvBzaCXK9EWRTEUn6eT36yZYb501qr1z/cKaZd//mKy2ee6iPzMlCLGMBvEYTwmIicv2nUQlz6gVnvyhkZcBRjQO7mmpZ/qqz07rbFAIaIz+SODljctlH3/1u9PugKUGJzMHDZAmCP/AP5VuuMfMRreHJrd5Sz9RMYfBz2iqWXmS9z0SyuA4CmaCatsHu8Rnb6zFKafmtS9pk+ReTXyCvrpw6a5IdhYHBB47pjjU7iKUX+jilYIfVJSQ/JjbO/cZO7bbYjFhF/adV0o=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Study-of-a-Woman_1373
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy